### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by M-Colley** [andreybicalho/vrpdr#3]
Hey there!

Is there already a plan when to upload the needed config files? Otherwise, I believe this can't be used as I get 

FileNotFoundError: [Errno 2] No such file or directory: '../config/classes.names'

**Comment by andreybicalho** [comment]
Hey, the classes.names file I can provide, it has just one line with the LP word which means license plate, that is the only one class I trained YOLO with. Unfortunately, I can't provide the weights files because I don't have them anymore... it would require me to train YOLO and the Attention-OCR all over again and you know the drill...
